name: Destroy

on:
  workflow_dispatch:
    inputs:
      enviroment:
        type: choice
        description: Which enviroment to remove AWS resources for?
        options:
          - staging
          - prod

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform Destroy
        env:
            AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export TF_WORKSPACE=${{ github.event.inputs.enviroment }}
          cd infra/
          docker compose run --rm terraform -chdir=deploy/ init
          docker compose run --rm terraform -chdir=deploy/ destroy -auto-approve

